### ISSUE TITLE
一些建议

### ISSUE THREAD

**Issue by PearsSauce** [qimu666/qi-api#14]
1. 接口流控，接口容易被刷；
2. qq登录，这是目前最常用得登录方式；

**Comment by qimu666** [comment]
可以自己尝试增加一下，这边可以给你一点建议:
1.第一个问题，可以尝试使用漏桶限流，令牌桶限流来进行优化，
2.第二个问题，可以尝试申请qq互联，创建应用，接入相应的功能，也可以使用第三方的接口服务来调用qq登录
