### ISSUE TITLE
启动gateway报错

### ISSUE THREAD

**Issue by Mrdyzjgd** [qimu666/qi-api#15]
启动gateway的时候，报错没有服务提供者，qi-api-interface已经启动了，还是报错
java.lang.IllegalStateException: Failed to check the status of the service com.qimu.qiapicommon.service.inner.InnerUserService. No provider available for the service com.qimu.qiapicommon.service.inner.InnerUserService from the url consumer://10.200.31.204/com.qimu.qiapicommon.service.inner.InnerUserService?application=dubbo-springboot-demo-provider&background=false&dubbo=2.0.2&file.cache=false&interface=com.qimu.qiapicommon.service.inner.InnerUserService&methods=getInvokeUserByAccessKey&pid=69912&qos.enable=false&register.ip=10.200.31.204&release=3.0.9&side=consumer&sticky=false&timestamp=1708241846977 to the consumer 10.200.31.204 use dubbo version 3.0.9

**Comment by qimu666** [comment]
先启动后端，在启动网关
