### ISSUE TITLE
本地调用

### ISSUE THREAD

**Issue by guicaizhici** [qimu666/qi-api#16]
你好，我在本地运行测试调用出现如图下面报错，该如何解决呢？
Unable to make field protected java.lang.String java.net.HttpURLConnection.method accessible: module java.base does not \"opens java.net\" to unnamed module @305b7c14
![0046f5c039cf1b26afaa43c3a920103](https://github.com/qimu666/qi-api/assets/68894564/9f18123f-5a73-4dd1-88ef-4ff27fff0944)

**Comment by qimu666** [comment]
> 你好，我在本地运行测试调用出现如图下面报错，该如何解决呢？
> Unable to make field protected java.lang.String java.net.HttpURLConnection.method accessible: module java.base does not \"opens java.net\" to unnamed module @305b7c14
> ![0046f5c039cf1b26afaa43c3a920103](https://github.com/qimu666/qi-api/assets/68894564/9f18123f-5a73-4dd1-88ef-4ff27fff0944)
> 

确认一下jdk版本，可以切换到1.8试试，这个是sdk反射出现错误，Java9之后引入了module模块的概念，而不同module模块间是不允许使用反射来访问非public的字段/方法/构造函数（field/method/constructor），除非被访问的目标模块为反射设置open即允许自身被其他模块进行non-public反射访问。

**Comment by guicaizhici** [comment]
哦哦哦好的，换了jdk之后问题成功解决了，谢谢！学到了一个Java小知识！但是随后出现了“请正确配置接口凭证”，请问这个该在哪里配置呢？
![Uploading 054ef6ccb5d07e03e7509e6110ff9ae.png…]()

**Comment by guicaizhici** [comment]
哦哦哦好的，换了jdk之后问题成功解决了，谢谢！学到了一个Java小知识！但是随后出现了“请正确配置接口凭证”，请问这个该在哪里配置呢？
![054ef6ccb5d07e03e7509e6110ff9ae](https://github.com/qimu666/qi-api/assets/68894564/92d1c557-99e5-45c5-979a-c4330037cc5a)

**Comment by qimu666** [comment]
不修改sdk地址去api.qimuu.icu网站上获取ak，sk，填写到数据库中，修改sdk配置为本地需要把接口地址更新为本地网关地址












柒木接口
***@***.***






---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年3月13日(周三) 上午9:11
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [qimu666/qi-api] 本地调用 (Issue #16)




 
哦哦哦好的，换了jdk之后问题成功解决了，谢谢！学到了一个Java小知识！但是随后出现了“请正确配置接口凭证”，请问这个该在哪里配置呢？
 054ef6ccb5d07e03e7509e6110ff9ae.png (view on web)

**Comment by guicaizhici** [comment]
好的解决了谢谢！
