### ISSUE TITLE
本地测试调用报错

### ISSUE THREAD

**Issue by WendaJackie** [qimu666/qi-api#17]
博主你好，本地测试调用的时候出现了如下的Bug，后台也没有任何的报错，Nacos也开着在，Nacos中也能找到这个服务，但是调用不通过。
![Snipaste_2024-03-23_02-44-10](https://github.com/qimu666/qi-api/assets/94043712/6e22eefd-0095-479f-95ac-230b0b284b92)
![Snipaste_2024-03-23_02-52-20](https://github.com/qimu666/qi-api/assets/94043712/3aed9ea6-ce87-4113-8c15-521b1affd90e)

**Comment by WendaJackie** [comment]
实际报错详情如下：
{
    "code": 0,
    "data": {
        "code": 403,
        "errorMessage": "Failed to invoke the method getInvokeUserByAccessKey in the service com.qimu.qiapicommon.service.inner.InnerUserService. No provider available for the service com.qimu.qiapicommon.service.inner.InnerUserService from registry localhost:8848 on the consumer 172.17.0.1 using the dubbo version 3.0.9. Please check if the providers have been started and registered."
    },
    "message": "ok"
}

**Comment by qimu666** [comment]
尝试重新`install` common项目，重新更新依赖试试。先启动后端->网关

**Comment by WendaJackie** [comment]
common安装是可以安，但是还是如上图的错误，是不是还需要改application.yml里的配置，或者是我的nacos版本的问题

**Comment by WendaJackie** [comment]
和我后面提出的那个issue的问题一样，我想先在本地测试跑通一下，是不是得要修改qi-api-sdk里的gatewayHost的地址呢

**Comment by qimu666** [comment]
sdk有提供host配置api，nacos如果还是这样建议你更换本地版本试一下，我的版本是2.0.4

**Comment by WendaJackie** [comment]
最后：我没动nacos版本，本地的测试已经通过了，我把gatewayHost改成空字符串即可了，还有这个qi-api-sdk里的https://gateway.qimuu.icu/api是要上线的地址吗？
还有就是，获取ip的接口信息应该要修改一下了

**Comment by WendaJackie** [comment]
> 最后：我没动nacos版本，本地的测试已经通过了，我把gatewayHost改成空字符串即可了，还有这个qi-api-sdk里的[https://gateway.qimuu.icu/api是要上线的地址吗？](https://gateway.qimuu.icu/api%E6%98%AF%E8%A6%81%E4%B8%8A%E7%BA%BF%E7%9A%84%E5%9C%B0%E5%9D%80%E5%90%97%EF%BC%9F) 还有就是，获取ip的接口信息应该要修改一下了

好吧，其实这个不太对，应该在sdk里写死gateway的本地地址localhost:8090/api/**，等后面有上线需求了再改成真实的地址。

**Comment by qimu666** [comment]
sdk提供有host修改api，使用线上地址是为了方便sdk用户使用

**Comment by WendaJackie** [comment]
> sdk提供有host修改api，使用线上地址是为了方便sdk用户使用

好的，明白了，感谢！
