### ISSUE TITLE
尝试将网关更改为本地的网关后接口在线调试不通过。

### ISSUE THREAD

**Issue by LINK-URIBOH** [qimu666/qi-api#18]
我想问一下想把网关改到本地的网关需要修改哪些内容。
我修改了数据库的url以及qi-api-backend中application.yml的配置，但是在尝试调试时报错
{
    "code": 0,
    "data": {
        "code": 403,
        "errorMessage": "404 NOT_FOUND"
    },
    "message": "ok"
}
截图如下：
![image](https://github.com/qimu666/qi-api/assets/34745010/c90b60bd-2f35-4aa7-b84f-e223c61a48f9)

**Comment by qimu666** [comment]
本地调试建议使用localhost

**Comment by LINK-URIBOH** [comment]
> 本地调试建议使用localhost
我刚才研究了一下，发现这个拼接请求链接似乎有些问题
![image](https://github.com/qimu666/qi-api/assets/34745010/f498a682-0038-4874-9d6c-7081c705ca8b)
我在本地改了sdk中拼接请求链接的路径之后就可以跑通了。
![image](https://github.com/qimu666/qi-api/assets/34745010/a80f25d0-5637-4577-a515-7636f4b609b2)
![image](https://github.com/qimu666/qi-api/assets/34745010/a2e32afb-d08e-4841-84c9-0655f89cbbee)
不知道是我的问题还是这个逻辑有点问题。

**Comment by qimu666** [comment]
网关和接口前缀保持一致就可以

**Comment by LINK-URIBOH** [comment]
> 网关和接口前缀保持一致就可以

主要是这方法调用的时候，穿参传的是接口的完整而不是前缀。
