### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Galaxy-to-turn** [qimu666/qi-api#27]
### 提问自检：

- [ ] 我已确认目前没有类似 issue
- [ ] 我已确认我已升级到最新版本
- [ ] 我已完整查看过项目 README，尤其是常见问题部分
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [ ] 我理解并认可上述内容，并理解项目维护者精力有限，不遵循规则的 issue 可能会被无视或直接关闭

### JDk版本：

8

### 问题描述：

你好，现在好像无法登录了，不知道是什么bug /(ㄒoㄒ)/~~

**Comment by qimu666** [comment]
可以自行搭建一下。线上因服务器配置低，自动掉线了
