### ISSUE TITLE
无法删除未付款订单

### ISSUE THREAD

**Issue by quankengshan** [qimu666/qi-api#8]
用户ID：1744911392902868994
地址：https://api.qimuu.icu/order/list
涉及订单编号：order_58346913854540595023
报错内容：Failed to convert value of type 'java.lang.String' to required type 'int'; nested exception is java.lang.NumberFormatException: For input string: "1744912561268191233"

**Comment by qimu666** [comment]
感谢🙏🏻您的反馈，类型转换出现了问题，调试的时候未调试到












柒木接口
***@***.***






---原始邮件---
发件人: "Brandon ***@***.***&gt;
发送时间: 2024年1月10日(周三) 下午4:56
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [qimu666/qi-api] 无法删除未付款订单 (Issue #8)




 
用户ID：1744911392902868994
 地址：https://api.qimuu.icu/order/list
 涉及订单编号：order_58346913854540595023
 报错内容：Failed to convert value of type 'java.lang.String' to required type 'int'; nested exception is java.lang.NumberFormatException: For input string: "1744912561268191233"
