### ISSUE TITLE
无法打包报错

### ISSUE THREAD

**Issue by quankengshan** [qimu666/qi-api#9]
C:\Users\lenovo\.jdks\corretto-1.8.0_392\bin\java.exe -Dmaven.multiModuleProjectDirectory=C:\Users\lenovo\Desktop\qi-api-后端 -Djansi.passthrough=true "-Dmaven.home=D:\JetBrains\IntelliJ IDEA 2023.2.1\plugins\maven\lib\maven3" "-Dclassworlds.conf=D:\JetBrains\IntelliJ IDEA 2023.2.1\plugins\maven\lib\maven3\bin\m2.conf" "-Dmaven.ext.class.path=D:\JetBrains\IntelliJ IDEA 2023.2.1\plugins\maven\lib\maven-event-listener.jar" "-javaagent:D:\JetBrains\IntelliJ IDEA 2023.2.1\lib\idea_rt.jar=55153:D:\JetBrains\IntelliJ IDEA 2023.2.1\bin" -Dfile.encoding=UTF-8 -classpath "D:\JetBrains\IntelliJ IDEA 2023.2.1\plugins\maven\lib\maven3\boot\plexus-classworlds-2.7.0.jar;D:\JetBrains\IntelliJ IDEA 2023.2.1\plugins\maven\lib\maven3\boot\plexus-classworlds.license" org.codehaus.classworlds.Launcher -Didea.version=2023.3.2 -s D:\apache-maven\conf\settings.xml package
[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for com.qimu:qi-api-backend:0.0.1: The following artifacts could not be resolved: com.qimu:qi-api:pom:0.0.1 (absent): com.qimu:qi-api:pom:0.0.1 was not found in https://maven.aliyun.com/repository/public during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of nexus-aliyun has elapsed or updates are forced and 'parent.relativePath' points at no local POM @ line 6, column 13
[FATAL] Non-resolvable parent POM for com.qimu:qi-api-interface:0.0.1: The following artifacts could not be resolved: com.qimu:qi-api:pom:0.0.1 (absent): com.qimu:qi-api:pom:0.0.1 was not found in https://maven.aliyun.com/repository/public during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of nexus-aliyun has elapsed or updates are forced and 'parent.relativePath' points at no local POM @ line 5, column 13
[FATAL] Non-resolvable parent POM for com.qimu:qi-api-gateway:0.0.1-SNAPSHOT: The following artifacts could not be resolved: com.qimu:qi-api:pom:0.0.1 (absent): com.qimu:qi-api:pom:0.0.1 was not found in https://maven.aliyun.com/repository/public during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of nexus-aliyun has elapsed or updates are forced and 'parent.relativePath' points at no local POM @ line 5, column 13
[FATAL] Non-resolvable parent POM for com.qimu:qi-api-common:0.0.1: The following artifacts could not be resolved: com.qimu:qi-api:pom:0.0.1 (absent): com.qimu:qi-api:pom:0.0.1 was not found in https://maven.aliyun.com/repository/public during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of nexus-aliyun has elapsed or updates are forced and 'parent.relativePath' points at no local POM @ line 5, column 13
 @ 
[ERROR] The build could not read 4 projects -> [Help 1]
[ERROR]   
[ERROR]   The project com.qimu:qi-api-backend:0.0.1 (C:\Users\lenovo\Desktop\qi-api-后端\qi-api-backend\pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for com.qimu:qi-api-backend:0.0.1: The following artifacts could not be resolved: com.qimu:qi-api:pom:0.0.1 (absent): com.qimu:qi-api:pom:0.0.1 was not found in https://maven.aliyun.com/repository/public during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of nexus-aliyun has elapsed or updates are forced and 'parent.relativePath' points at no local POM @ line 6, column 13 -> [Help 2]
[ERROR]   
[ERROR]   The project com.qimu:qi-api-interface:0.0.1 (C:\Users\lenovo\Desktop\qi-api-后端\qi-api-interface\pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for com.qimu:qi-api-interface:0.0.1: The following artifacts could not be resolved: com.qimu:qi-api:pom:0.0.1 (absent): com.qimu:qi-api:pom:0.0.1 was not found in https://maven.aliyun.com/repository/public during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of nexus-aliyun has elapsed or updates are forced and 'parent.relativePath' points at no local POM @ line 5, column 13 -> [Help 2]
[ERROR]   
[ERROR]   The project com.qimu:qi-api-gateway:0.0.1-SNAPSHOT (C:\Users\lenovo\Desktop\qi-api-后端\qi-api-gateway\pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for com.qimu:qi-api-gateway:0.0.1-SNAPSHOT: The following artifacts could not be resolved: com.qimu:qi-api:pom:0.0.1 (absent): com.qimu:qi-api:pom:0.0.1 was not found in https://maven.aliyun.com/repository/public during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of nexus-aliyun has elapsed or updates are forced and 'parent.relativePath' points at no local POM @ line 5, column 13 -> [Help 2]
[ERROR]   
[ERROR]   The project com.qimu:qi-api-common:0.0.1 (C:\Users\lenovo\Desktop\qi-api-后端\qi-api-common\pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for com.qimu:qi-api-common:0.0.1: The following artifacts could not be resolved: com.qimu:qi-api:pom:0.0.1 (absent): com.qimu:qi-api:pom:0.0.1 was not found in https://maven.aliyun.com/repository/public during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of nexus-aliyun has elapsed or updates are forced and 'parent.relativePath' points at no local POM @ line 5, column 13 -> [Help 2]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException

进程已结束，退出代码为 1

**Comment by qimu666** [comment]
配置maven镜像为阿里云镜像试试

**Comment by quankengshan** [comment]
> 配置maven镜像为阿里云镜像试试

阿里和腾讯都试过了，依旧是报错。且前端管理页 本地调试，接口管理 控制台报错

**Comment by qimu666** [comment]
清空本地maven仓库 ，重新构建一下项目试试

**Comment by quankengshan** [comment]
> 清空本地maven仓库 ，重新构建一下项目试试

清空，配置了阿里云镜像，打包还是有问题，拉取得最新得后端master，报错内容如下：
C:\Users\lenovo\.jdks\corretto-1.8.0_392\bin\java.exe -Dmaven.multiModuleProjectDirectory=C:\Users\lenovo\Desktop\qi-api-master -Djansi.passthrough=true -Dmaven.home=D:\apache-maven-3.9.3 -Dclassworlds.conf=D:\apache-maven-3.9.3\bin\m2.conf "-Dmaven.ext.class.path=D:\JetBrains\IntelliJ IDEA 2023.2.1\plugins\maven\lib\maven-event-listener.jar" "-javaagent:D:\JetBrains\IntelliJ IDEA 2023.2.1\lib\idea_rt.jar=64788:D:\JetBrains\IntelliJ IDEA 2023.2.1\bin" -Dfile.encoding=UTF-8 -classpath D:\apache-maven-3.9.3\boot\plexus-classworlds-2.7.0.jar;D:\apache-maven-3.9.3\boot\plexus-classworlds.license org.codehaus.classworlds.Launcher -Didea.version=2023.3.2 -s D:\apache-maven-3.9.3\conf\settings.xml package
[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for com.qimu:qi-api-backend:0.0.1: The following artifacts could not be resolved: com.qimu:qi-api:pom:0.0.1 (absent): com.qimu:qi-api:pom:0.0.1 was not found in https://maven.aliyun.com/repository/public during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of aliyunmaven has elapsed or updates are forced and 'parent.relativePath' points at no local POM @ line 6, column 13
[FATAL] Non-resolvable parent POM for com.qimu:qi-api-interface:0.0.1: The following artifacts could not be resolved: com.qimu:qi-api:pom:0.0.1 (absent): com.qimu:qi-api:pom:0.0.1 was not found in https://maven.aliyun.com/repository/public during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of aliyunmaven has elapsed or updates are forced and 'parent.relativePath' points at no local POM @ line 5, column 13
[FATAL] Non-resolvable parent POM for com.qimu:qi-api-gateway:0.0.1-SNAPSHOT: The following artifacts could not be resolved: com.qimu:qi-api:pom:0.0.1 (absent): com.qimu:qi-api:pom:0.0.1 was not found in https://maven.aliyun.com/repository/public during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of aliyunmaven has elapsed or updates are forced and 'parent.relativePath' points at no local POM @ line 5, column 13
[FATAL] Non-resolvable parent POM for com.qimu:qi-api-common:0.0.1: The following artifacts could not be resolved: com.qimu:qi-api:pom:0.0.1 (absent): com.qimu:qi-api:pom:0.0.1 was not found in https://maven.aliyun.com/repository/public during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of aliyunmaven has elapsed or updates are forced and 'parent.relativePath' points at no local POM @ line 5, column 13
 @ 
[ERROR] The build could not read 4 projects -> [Help 1]
[ERROR]   
[ERROR]   The project com.qimu:qi-api-backend:0.0.1 (C:\Users\lenovo\Desktop\qi-api-master\qi-api-backend\pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for com.qimu:qi-api-backend:0.0.1: The following artifacts could not be resolved: com.qimu:qi-api:pom:0.0.1 (absent): com.qimu:qi-api:pom:0.0.1 was not found in https://maven.aliyun.com/repository/public during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of aliyunmaven has elapsed or updates are forced and 'parent.relativePath' points at no local POM @ line 6, column 13 -> [Help 2]
[ERROR]   
[ERROR]   The project com.qimu:qi-api-interface:0.0.1 (C:\Users\lenovo\Desktop\qi-api-master\qi-api-interface\pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for com.qimu:qi-api-interface:0.0.1: The following artifacts could not be resolved: com.qimu:qi-api:pom:0.0.1 (absent): com.qimu:qi-api:pom:0.0.1 was not found in https://maven.aliyun.com/repository/public during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of aliyunmaven has elapsed or updates are forced and 'parent.relativePath' points at no local POM @ line 5, column 13 -> [Help 2]
[ERROR]   
[ERROR]   The project com.qimu:qi-api-gateway:0.0.1-SNAPSHOT (C:\Users\lenovo\Desktop\qi-api-master\qi-api-gateway\pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for com.qimu:qi-api-gateway:0.0.1-SNAPSHOT: The following artifacts could not be resolved: com.qimu:qi-api:pom:0.0.1 (absent): com.qimu:qi-api:pom:0.0.1 was not found in https://maven.aliyun.com/repository/public during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of aliyunmaven has elapsed or updates are forced and 'parent.relativePath' points at no local POM @ line 5, column 13 -> [Help 2]
[ERROR]   
[ERROR]   The project com.qimu:qi-api-common:0.0.1 (C:\Users\lenovo\Desktop\qi-api-master\qi-api-common\pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for com.qimu:qi-api-common:0.0.1: The following artifacts could not be resolved: com.qimu:qi-api:pom:0.0.1 (absent): com.qimu:qi-api:pom:0.0.1 was not found in https://maven.aliyun.com/repository/public during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of aliyunmaven has elapsed or updates are forced and 'parent.relativePath' points at no local POM @ line 5, column 13 -> [Help 2]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException

进程已结束，退出代码为 1

**Comment by quankengshan** [comment]
看样子是 阿里云镜像库 没找到这个文件

**Comment by qimu666** [comment]
尝试一下先安装common到本地后，刷新依赖在打包呢
